name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: u362398019
          server: 46.202.158.34
          port: 65002
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './*'
          remote_path: './'
          sftp_only: true
