name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    name: Upload files via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: u362398019
          server: 46.202.158.34
          port: 65002
          local_path: './*'
          remote_path: '/public_html/'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}
