name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload files via FTPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: FTPS Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ie-viie.org
          username: u362398019
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./
          server-dir: /public_html/
